### ISSUE TITLE
Set Time incorrectly

### ISSUE THREAD

**Issue by mohsinous** [inolen/redream#187]
hi... when i change time zone in windows redream set it vice versa. for example its 00:00 on UTC when set it to +03:30 (Tehran-Iran) redream shows 20:30 instead of 03:30!!!!
![2017-10-11_17-10-52](https://user-images.githubusercontent.com/32609205/31445892-015e2f82-aeac-11e7-9468-6bce3f13dcd8.jpg)

**Comment by bigboo3000** [comment]
Yes I wrote this in the sturmwind issue but it's better here:

about time offset : I changed my system date to 31/10/2017 (winter time in Europe) and the offset between system time and dreamcast time is now 2 hours instead of 3 hours.

I think the problem in the new code in bios.c is :
time_t curr_time_utc = mktime(**gmtime**(&curr_time_local));
I think it should be "localtime" instead of "gmtime" on Windows

**Comment by inolen** [comment]
Hopefully fixed with https://github.com/inolen/redream/commit/3c8c2cf81c49602384c98a1bda8150d256e7d5d9.

**Comment by bigboo3000** [comment]
I confirm that time is now displayed correctly on my windows 10 machine.

**Comment by mohsinous** [comment]
I can confirm that the problem is fixed
