### ISSUE TITLE
SDL version bump

### ISSUE THREAD

**Issue by davidgfnet** [inolen/redream#28]
Hey! Great work man, keep it up, just awesome really.
You might want to update SDL to 2.0.6 at least, there seems to be an issue with a missing symbol (fails to link in my computer) called wl_proxy_marshal_constructor_versioned
I manually patched SDL in deps/ and it works for me now. Apparently 2.0.6 fixes this from what I read. The relevant patch that I applied is: https://hg.libsdl.org/SDL/rev/330f500d5815

Thanks again man!

**Comment by inolen** [comment]
Thanks for the feedback!

Instead of upgrading SDL, I think I'm inclined to swap to GLFW. I'll try to take a stab at this soon.

**Comment by RenatoUtsch** [comment]
GLFW is awesome, I use it a lot for my OpenGL/Vulkan projects, but it doesn't offer any sound libraries. How are you going to implement that?

**Comment by MerryMage** [comment]
Would suggest using libsoundio if you wanted something that focuses just on sound that is cross-platform and well maintained.

**Comment by inolen** [comment]
@RenatoUtsch I was planning on just writing each backend manually (I wrote the initial ALSA one already), but I'll give libsoundio a check.

The issue comes up that I'm contemplating using the audio queuing to synchronize the emulator, which may either not be possible in SDL or introduce even more latency making it not work well.

@MerryMage cheers, will take a look at that. As much as I want to get audio in, I'm not very enthused about writing coreaudio / whatever windows uses backends.

**Comment by RenatoUtsch** [comment]
@inolen then GLFW will be much much better than SDL. I can't recommend it enough.

Great! I was in need of a portable audio library, thanks @MerryMage!

**Comment by inolen** [comment]
Closing this as glfw is in now.
