### ISSUE TITLE
Xbox-One UWP Port ?

### ISSUE THREAD

**Issue by wiired24** [inolen/redream#86]
Hi Inolen,

Currently there is alot of demand for a Sega Dreamcast emulator for UWP devices such as Xbox One. Quite a few of us in the community are impressed with your Dreamcast emulator and would like to see it ported to the UWP Platform. If you do decide to begin work on a port this may also help attract other devs/users to your project who may have never heard of it before.

Thanks in advance for the consideration

**Comment by inolen** [comment]
Not sure I'm very familiar with the Xbox ecosystem. Would this app have to be approved / distributed by Microsoft, or ...?

**Comment by twinaphex** [comment]
It wouldn't be allowed on the App Store since MS has banned emulators on their store. So the only way for an Xbox user to use it is if they first pay to get 'dev mode' unlocked, then they have to switch to that in order to play homebrew, and then switch it back to enduser mode again to have it play retail games again.

It's very much a niche.

**Comment by inolen** [comment]
In that case, I don't think I'll be working on direct support for this anytime soon.

**Comment by wiired24** [comment]
Well I mean emulation itself with regards to consoles is kind of a niche hobby anyways, but regardless thanks for the consideration
